Avoid ClassCastException when converting integer to long
Casting an Integer object via (long) was causing the exception

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

to be thrown when writing an INT64 array to Spanner from a BigQuery
INTEGER Avro input.